export const LAKHISARAI_SEO_KEYWORDS: string[] = [
  // List 1 Tags
  "Best Physical Academy in Lakhisarai",
  "No.1 Physical Academy in Lakhisarai",
  "Top Physical Academy in Lakhisarai",
  "Best Army Coaching in Lakhisarai",
  "Top Army Coaching in Lakhisarai",
  "Best Defence Academy in Lakhisarai",
  "Top Defence Academy in Lakhisarai",
  "Best Police Coaching in Lakhisarai",
  "Top Police Coaching in Lakhisarai",
  "Best Bihar Police Coaching in Lakhisarai",
  "Best SSC GD Coaching in Lakhisarai",
  "Best Agniveer Coaching in Lakhisarai",
  "Best Running Academy in Lakhisarai",
  "Best Fitness Academy in Lakhisarai",
  "Best Physical Training Institute in Lakhisarai",
  "Top Physical Training Institute in Lakhisarai",
  "Best Government Job Physical Coaching in Lakhisarai",
  "Army Physical Coaching in Lakhisarai",
  "Police Physical Coaching in Lakhisarai",
  "Defence Physical Coaching in Lakhisarai",
  "Military Physical Training in Lakhisarai",
  "Army Running Training in Lakhisarai",
  "Police Running Training in Lakhisarai",
  "Defence Running Training in Lakhisarai",
  "Physical Fitness Training in Lakhisarai",
  "Outdoor Physical Training in Lakhisarai",
  "Professional Physical Training in Lakhisarai",
  "Advanced Physical Training in Lakhisarai",
  "Physical Exam Coaching in Lakhisarai",
  "PET Coaching in Lakhisarai",
  "PST Coaching in Lakhisarai",
  "Army Selection Preparation Lakhisarai",
  "Police Selection Preparation Lakhisarai",
  "Defence Selection Preparation Lakhisarai",
  "Army Bharti Coaching Lakhisarai",
  "Police Bharti Coaching Lakhisarai",
  "Defence Bharti Coaching Lakhisarai",
  "Indian Army Bharti Preparation Lakhisarai",
  "Agniveer Bharti Coaching Lakhisarai",
  "Best Army Ground in Lakhisarai",
  "Best Running Ground in Lakhisarai",
  "Physical Fitness Centre in Lakhisarai",
  "Physical Fitness Classes in Lakhisarai",
  "Morning Fitness Training Lakhisarai",
  "Evening Fitness Training Lakhisarai",
  "Army Fitness Training Lakhisarai",
  "Police Fitness Training Lakhisarai",
  "Defence Fitness Training Lakhisarai",
  "Physical Coaching Centre Lakhisarai",
  "Army Training Centre Lakhisarai",
  "Defence Training Centre Lakhisarai",
  "Police Training Centre Lakhisarai",
  "Best Coaching Institute in Lakhisarai",
  "Top Coaching Institute in Lakhisarai",
  "Best Academy for Army Preparation",
  "Best Academy for Police Preparation",
  "Best Academy for Defence Preparation",
  "Best Physical Academy Near Me",
  "Top Physical Academy Near Me",
  "Army Coaching Near Me in Bihar",
  "Defence Academy Near Me in Bihar",
  "Police Coaching Near Me in Bihar",
  "Best Physical Trainer in Lakhisarai",
  "Experienced Physical Trainer Lakhisarai",
  "Physical Training Classes Lakhisarai",
  "Army Recruitment Training Lakhisarai",
  "Police Recruitment Training Lakhisarai",
  "Defence Recruitment Training Lakhisarai",
  "Army Physical Test Preparation",
  "Police Physical Test Preparation",
  "Defence Physical Test Preparation",
  "Best Sports Academy in Lakhisarai",
  "Top Sports Academy in Lakhisarai",
  "Physical Coaching for Government Jobs",
  "Physical Training for Competitive Exams",
  "Best Fitness and Running Academy Lakhisarai",
  "Army Coaching with Physical Training Lakhisarai",
  "Police Coaching with Physical Training Lakhisarai",
  "Defence Coaching with Physical Training Lakhisarai",
  "Physical Academy Bihar",
  "Best Physical Academy Bihar",
  "Top Physical Academy Bihar",
  "No.1 Defence Academy Bihar",
  "No.1 Army Coaching Bihar",
  "No.1 Police Coaching Bihar",
  "Best Agniveer Academy Bihar",
  "Best Defence Coaching Bihar",
  "Best Army Training Bihar",
  "Best Police Training Bihar",
  "Best Running Academy Bihar",
  "Best Fitness Academy Bihar",
  "Lakhisarai Physical Training Center",
  "Lakhisarai Army Training Center",
  "Lakhisarai Defence Training Center",
  "Lakhisarai Police Training Center",
  "Lakhisarai Physical Fitness Center",
  "Lakhisarai Recruitment Training Center",
  "Best Career Academy Lakhisarai",
  "Top Career Academy Lakhisarai",
  "Best Physical Coaching in Bihar",
  "Top Physical Coaching in Bihar",

  // List 2 Tags
  "Lakhisarai",
  "Lakhisarai Bihar",
  "Lakhisarai Academy",
  "Lakhisarai Physical Academy",
  "Physical Academy Lakhisarai",
  "Best Physical Academy Lakhisarai",
  "Top Physical Academy Lakhisarai",
  "Physical Training Lakhisarai",
  "Army Coaching Lakhisarai",
  "Army Academy Lakhisarai",
  "Army Physical Training Lakhisarai",
  "Army Preparation Lakhisarai",
  "Agniveer Coaching Lakhisarai",
  "Agniveer Physical Training",
  "Indian Army Coaching Lakhisarai",
  "Indian Army Physical Training",
  "Military Training Lakhisarai",
  "Defence Academy Lakhisarai",
  "Defence Coaching Lakhisarai",
  "Defence Physical Training",
  "Police Coaching Lakhisarai",
  "Police Physical Training Lakhisarai",
  "Bihar Police Coaching",
  "Bihar Police Physical Training",
  "SSC GD Coaching Lakhisarai",
  "SSC GD Physical Training",
  "CRPF Physical Training",
  "BSF Physical Training",
  "CISF Physical Training",
  "ITBP Physical Training",
  "Railway Physical Training",
  "Home Guard Coaching Bihar",
  "Running Academy Lakhisarai",
  "Running Practice Lakhisarai",
  "Ground Training Lakhisarai",
  "Fitness Academy Lakhisarai",
  "Fitness Training Lakhisarai",
  "Gym and Physical Training Lakhisarai",
  "Sports Academy Lakhisarai",
  "Athletic Training Lakhisarai",
  "Morning Running Lakhisarai",
  "Government Job Physical Preparation",
  "Physical Test Preparation Bihar",
  "PET Preparation Bihar",
  "PST Preparation Bihar",
  "Army Running Coaching",
  "1600 Meter Running Training",
  "Long Run Practice Lakhisarai",
  "Physical Fitness Coaching",
  "Best Defence Academy Bihar",
  "Best Army Coaching Bihar",
  "Best Police Coaching Bihar",
  "Lakhisarai Coaching Institute",
  "Coaching Centre Lakhisarai",
  "Training Institute Lakhisarai",
  "Career Academy Lakhisarai",
  "Job Preparation Lakhisarai",
  "Competitive Exam Training Bihar",
  "Youth Fitness Training Bihar",
  "Army Recruitment Coaching",
  "Police Recruitment Coaching",
  "Defence Recruitment Coaching",
  "Government Recruitment Training",
  "Physical Instructor Lakhisarai",
  "Running Coach Lakhisarai",
  "Fitness Coach Lakhisarai",
  "Outdoor Fitness Training",
  "Physical Fitness Center",
  "Best Running Ground Lakhisarai",
  "Lakhisarai Fitness Center",
  "Lakhisarai Training Center",
  "Near Me Physical Academy",
  "Near Me Army Coaching",
  "Near Me Police Coaching",
  "Near Me Defence Academy",
  "Best Academy Near Me",
  "Best Physical Training Near Me",
  "Army Coaching Near Me",
  "Police Coaching Near Me",
  "Defence Coaching Near Me",
  "Physical Coaching Bihar",
  "Army Training Bihar",
  "Police Training Bihar",
  "Defence Training Bihar",
  "Agniveer Academy Bihar",
  "Army Ground Practice Bihar",
  "Physical Test Coaching Bihar",
  "Fitness Institute Bihar",
  "Government Job Coaching Bihar",
  "Physical Exam Preparation",
  "Running and Fitness Academy",
  "Lakhisarai Sports Ground",
  "Lakhisarai Fitness Academy",
  "Lakhisarai Defence Academy",
  "Lakhisarai Army Academy",
  "Lakhisarai Police Academy",
  "Lakhisarai Running Academy",
  "Lakhisarai Government Job Coaching",
  "Best Academy in Lakhisarai",
  "Top Coaching in Lakhisarai",
  "Lakhisarai Education and Training"
];
